name: Measure coverage

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # gradlew 파일 권한 지정
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # test 실행
      - name: Run tests
        run: ./gradlew test

      # Jacoco를 이용해 테스트 커버리지 측정
      - name: Build Jacoco
        run: ./gradlew jacocoRootReport

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            ${{ github.workspace }}/module-core/build/reports/jacoco/test/jacocoTestReport.xml,
            ${{ github.workspace }}/module-api/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 30
          min-coverage-changed-files: 50