:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 3

= API 문서

[[API-개요]]

[[오류-응답]]
== 오류 응답
operation::error-response[snippets='response-body,response-fields']

[[카테고리-API]]
== 카테고리 API

[[카테고리-목록]]
=== 카테고리 목록
operation::categories-list[snippets='http-request,http-response']

[[이미지-API]]
== 이미지 API

[[이미지-업로드]]
=== 이미지 업로드
operation::images-upload[snippets='http-request,request-parts,query-parameters,http-response,response-fields']

[[지역-API]]
== 지역 API

[[지역-목록]]
=== 지역 목록 조회
operation::regions-list[snippets='http-request,http-response']

[[지역-변경]]
=== 사용자 지역 변경
operation::update-user-region[snippets='http-request,query-parameters,http-response,response-fields']

[[게시물-API]]
== 게시물 API

[[게시물-목록]]
=== 게시물 목록 조회
operation::posts-list[snippets='http-request,query-parameters,http-response,response-fields']

[[게시물-조회]]
=== 게시물 개별 조회
operation::get-post[snippets='http-request,query-parameters,http-response,response-fields']

[[게시물-생성]]
=== 게시물 생성
operation::create-post[snippets='http-request,request-fields,http-response,response-fields']

[[게시물-수정]]
=== 게시물 수정
operation::update-post[snippets='http-request,query-parameters,http-response,response-fields']

[[게시물-삭제]]
=== 게시물 삭제
operation::delete-post[snippets='http-request,query-parameters,http-response']

